web:
  port: 8080

endpoints:
  - name: Main Website
    group: production
    url: "https://hamza-alsoodani.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"

  - name: Monitoring Dashboard
    group: production
    url: "https://tm.hamza-alsoodani.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"
  
  - name: ECR Registry
    group: aws
    url: "https://076056288980.dkr.ecr.eu-west-2.amazonaws.com"
    interval: 5m
    conditions:
      - "[STATUS] == 401"

  - name: SSL Certificate
    group: production
    url: "https://hamza-alsoodani.com"
    interval: 1h
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 720h"

  - name: DNS Resolution
    group: production
    url: "8.8.8.8"
    interval: 5m
    dns:
      query-name: "hamza-alsoodani.com"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"

  - name: Response Time
    group: production
    url: "https://tm.hamza-alsoodani.com"
    interval: 2m
    conditions:
      - "[RESPONSE_TIME] < 1000"




